// Role priority mapping for office bearers
const ROLE_PRIORITY = {
  'Student Representative': 1,
  'Chapter Advisor': 1,
  Advisor: 1,
  All: 1,
  WIE: 2,
  Chairperson: 2,
  TC: 2,
  'Technical Coordinator': 2,
  'Vice Chairperson': 3,
  Secretary: 4,
  Treasurer: 5,
  'Web Reporter': 6,
  'Student Activities Coordinator': 6,
  'Joint Secretary': 7,
  'WISP Coordinator': 8,
  ECC: 9,
  'Media Coordinator (ECC)': 9,
  'Professional Activities Chair': 9,
  'Professional Activities Coordinator': 9,
  'Student Activities Co-Coordinator': 9,
  'Media Coordinator': 9,
  'Educational Activities Coordinator': 10,
  'SB Coordinator': 10,
  'Industrial Relations Coordinator': 11,
  'Industry Relational Coordinator': 11,
  'Humanitarian Activities Chair': 12,
  'Humanitarian Activities Coordinator': 12,
  'Content Team': 12,
  'Publicity and Outreach Co-Coordinator': 12,
  'Project Coordinator': 13,
  'Membership Development Coordinator': 14,
  'Publicity and Outreach Coordinator': 15,
  'Publicity Outreach Coordinator': 15,
  'Associate Technical Coordinator': 16,
  'Associate student activities coordinator': 16,
  'Associate Student Activities Coordinator': 16,
  'WISP Co-Coordinator': 17,
  'Associate WISP Coordinator': 17,
  'Associate Project Coordinator': 18,
  'Associate Media Coordinator': 18,
  'Hub SR': 19,
  'Hub SR/HMDC Kochi': 19,
  'Hub SR /HMDC Kochi': 19,
  'MDC - Kochi Hub': 19,
  'MDC - Malabar Hub': 19,
  'MDC - Travancore Hub': 19,
  'Hub SR/HMDC Malabar': 19,
  'Hub SR /HMDC Malalbar': 19,
  'Hub SR/HMDC Travancore': 19,
  'Hub SR /HMDC Travancore': 19,
  'Associate Membership Development Coordinator': 19,
  'Associate MDC': 19,
  'Outreach Coordinator': 20,
  'Associate Outreach Coordinator': 21,
  Webmaster: 22,
  'Associate Webmaster': 23,
  'Newsletter Editor': 24,
  'Newsletter Head': 24,
  'Content Lead': 25,
  'Content Head': 25,
  'Design Lead': 26,
  'Design Head': 26,
  'Design and Content Team': 27,
  'Design and Video Team': 27,
  'Web Intern': 28,
  'Video Intern': 28,
  'Technical Intern': 28,
  'Design Intern': 28
};
function sortByRolePriority(arr) {
  return arr.slice().sort((a, b) => {
    const aPriority = ROLE_PRIORITY[a.role] ?? 99;
    const bPriority = ROLE_PRIORITY[b.role] ?? 99;
    return aPriority - bPriority;
  });
}

export { sortByRolePriority, ROLE_PRIORITY };
